version: "3"
services:
  mongo:
    container_name: mongo-maxmilhas-api
    image: "mongo:latest"
    ports: 
      - "27018:27017"
    environment:
      MONGO_INITDB_DATABASE: 'admin'
      MONGO_INITDB_ROOT_USERNAME: 'root'
      MONGO_INITDB_ROOT_PASSWORD: 'root'
